graph
aepaysinger/data-structures-old pull request #13
Opened 2023-03-15 16:45 UTC by aepaysinger

2023-03-16 15:43 UTC, W-Ely requested changes
Some logical errors in add_edge need to be addressed.

2023-03-16 15:43 UTC, W-Ely commented on graph.py
> +        self.storage[value] = []
What assumption does this make about the value?

2023-03-16 15:43 UTC, W-Ely commented on graph.py
> +            if value2 in self.storage[value1]:
Why are these 2 ifs not combined?

2023-03-16 15:43 UTC, W-Ely commented on graph_test.py
> +    assert graph.storage == {4: [16, 8], 9: [81]}
Shouldn't 4, 16, 8, 9, and 81 all be nodes in this graph?

2023-03-16 15:43 UTC, W-Ely commented on graph_test.py
> +    assert graph.storage == {9: [81], 7: [49]}
If there is an edge between node 4 and node 16 (which should be in this graph as a node but isn't) and you delete node 4 it should remove node 4 and the connection to it from node 16.

2023-03-16 15:43 UTC, W-Ely commented on README.md
> +  * add_node(val): adds a new node with value ‘n’ to the graph
Just because there is a typo in the instructions doesn't mean you should carry it forward.

2023-03-16 15:44 UTC, aepaysinger commented on graph.py
> +        self.storage[value] = []
that it is already not there?

2023-03-16 15:52 UTC, aepaysinger commented on graph_test.py
> +    assert graph.storage == {4: [16, 8], 9: [81]}
i didnt think so but maybe i am not understanding what adding an edge does

2023-03-16 15:54 UTC, W-Ely commented on graph_test.py
> +    assert graph.storage == {4: [16, 8], 9: [81]}
Adding an edge adds a connection between `2` nodes

2023-03-16 15:56 UTC, aepaysinger commented on graph_test.py
> +    assert graph.storage == {9: [81], 7: [49]}
i think i have misunderstood something.
if you have a node 4 which as an edge connecting it to 16,
then 16 should be a node with a connection to 4?? so my self.storage should look like:
{
4: [16],
16: [4],
}
but i currently just have the first part

2023-03-16 16:00 UTC, aepaysinger commented on graph_test.py
> +    assert graph.storage == {9: [81], 7: [49]}
?

2023-03-16 16:01 UTC, W-Ely commented on graph.py
> +        self.storage[value] = []
That is true, you are making that assumption.  The instructions make it relatively safe to do so though.  What kinds of values can be used as keys in a dict?

2023-03-16 16:01 UTC, W-Ely commented on graph_test.py
> +    assert graph.storage == {9: [81], 7: [49]}
exactly.

2023-03-16 16:52 UTC, aepaysinger commented on graph.py
> +        self.storage[value] = []
strings, ints, etc....anything that is not mutable

2023-03-16 16:55 UTC, W-Ely commented on graph.py
> +        self.storage[value] = []
That's also true.  Probably Yup, so the assumption here is that only immutable values will be in this graph.  Might call this out as an assumption in the Readme.

2023-03-16 16:56 UTC, W-Ely commented on graph.py
> +            for node in self.storage:
No need to loop through all the nodes, you know which neighbors this node has.

2023-03-16 19:25 UTC, W-Ely approved these changes, later dismissed
🍠

2023-03-17 16:45 UTC, W-Ely approved these changes

2023-03-17 16:48 UTC, merged

2023-03-17 16:52 UTC, W-Ely reviewed
Take a look at these changes.  No need to apply them, just think about them.  With Python always think about if it's possible to remove an indentation/else elif.  If it is possible and the code isn't worse to read, prefer removing the indentations.  Less forked logic is easyer to follow.

2023-03-17 16:52 UTC, W-Ely commented on graph.py
> +            return value2 in self.storage[value1]
This is fine, but when creating if/elif,  But this would be a more common way to right this.
```suggestion
        if value1 not in self.storage or value2 not in self.storage[value1]::
            raise ValueError("Value does not exist")
        return value2 in self.storage[value1]
```

2023-03-17 16:52 UTC, W-Ely commented on graph.py
> +            raise ValueError("Value does not exist")
Alsoway think if there is a way to remove an indentation. like:
```suggestion
        if value not in self.storage:
             raise ValueError("Value does not exist")
        return self.storage[value]
```

2023-03-17 16:52 UTC, W-Ely commented on graph.py
> +            raise ValueError("Node does not exist")
```suggestion
        if value not in self.storage:
             raise ValueError("Node does not exist")
        for edge in self.storage[value]:
            self.storage[edge].remove(value)
        del self.storage[value]
```

2023-03-17 16:52 UTC, W-Ely commented on graph.py
> +            raise ValueError("Edge does not exist")
```suggestion
        if value1 not in self.storage or value2 not in self.storage[value1]:
            raise ValueError("Edge does not exist")
        self.storage[value1].remove(value2)
        self.storage[value2].remove(value1)
```